import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Dataset
from skimage.metrics import structural_similarity as ssim
from glob import glob
import cv2
import os
from sklearn.metrics import roc_auc_score

from spikingjelly.activation_based import ann2snn, functional
from utils import read_img, get_patch, patch2img
from network import AutoEncoder
from options import Options


class CalibrationDataset(Dataset):
    """Dataset for SNN conversion calibration"""
    
    def __init__(self, files, grayscale, patch_size, max_samples=100):
        self.files = files[:max_samples]
        self.grayscale = grayscale  
        self.patch_size = patch_size
        
    def __len__(self):
        return len(self.files)
        
    def __getitem__(self, idx):
        img = read_img(self.files[idx], self.grayscale)
        img = cv2.resize(img, (self.patch_size, self.patch_size))
        img = img / 255.0
        
        if self.grayscale:
            img = torch.FloatTensor(img).unsqueeze(0)
        else:
            img = torch.FloatTensor(img).permute(2, 0, 1)
        return img, torch.tensor(0)


class EnergyAnalyzer:
    """
    Energy consumption analyzer for ANN vs SNN comparison
    Based on ROLLS neuromorphic processor specifications:
    - ANN: 12.5pJ/FLOP (only count FLOPs)
    - SNN: 77fJ/SOP (only count SOPs - synaptic operations)
    """
    
    def __init__(self):
        self.snn_energy_per_sop = 77e-15  # 77 femtojoules per Synaptic Operation
        self.ann_energy_per_flop = 12.5e-12  # 12.5 picojoules per FLOP
        
        # Separate counters for different models
        self.flop_count = 0.0  # For ANN only
        self.sop_count = 0.0   # For SNN only
        self.spike_count = 0.0 # For debugging
        
    def reset_counters(self):
        """Reset all operation counters"""
        self.flop_count = 0.0
        self.sop_count = 0.0
        self.spike_count = 0.0
        
    def count_conv_flops(self, input_shape, output_shape, kernel_size, groups=1):
        """Count FLOPs for convolution operations (ANN only)"""
        batch_size, in_channels, in_h, in_w = input_shape
        _, out_channels, out_h, out_w = output_shape
        
        if isinstance(kernel_size, int):
            kernel_h = kernel_w = kernel_size
        else:
            kernel_h, kernel_w = kernel_size
            
        # Each output element requires: kernel_h * kernel_w * in_channels operations
        flops_per_element = float(kernel_h * kernel_w * in_channels // groups)
        total_elements = float(batch_size * out_channels * out_h * out_w)
        
        return flops_per_element * total_elements * 2.0  # multiply + add

    def count_activation_flops(self, input_shape):
        """Count FLOPs for activation functions (ANN only)"""
        return float(np.prod(input_shape))
        
    def ann_forward_hook(self, module, input, output):
        """Hook to count FLOPs in ANN forward pass"""
        input_shape = input[0].shape
        output_shape = output.shape
        
        if isinstance(module, (nn.Conv2d, nn.ConvTranspose2d)):
            flops = self.count_conv_flops(input_shape, output_shape, module.kernel_size, 
                                        getattr(module, 'groups', 1))
            self.flop_count += flops
            
            # Add bias FLOPs if present
            if module.bias is not None:
                self.flop_count += float(np.prod(output_shape))
                
        elif isinstance(module, (nn.ReLU, nn.Sigmoid, nn.LeakyReLU)):
            self.flop_count += self.count_activation_flops(output_shape)
            
        elif isinstance(module, nn.Linear):
            # Linear layer: input_features * output_features * batch_size * 2
            linear_flops = float(input_shape[-1] * output_shape[-1] * input_shape[0] * 2)
            self.flop_count += linear_flops

    def snn_forward_hook(self, module, input, output):
        """Hook to count SOPs in SNN forward pass (CORRECTED)"""
        module_type = str(type(module))
        
        if 'IFNode' in module_type:
            # Count spikes generated by this IFNode
            if isinstance(output, torch.Tensor):
                spikes = torch.sum(output > 0.5).item()
                self.spike_count += spikes
                
                # CORRECTED: Each spike = 1 SOP (synaptic operation)
                # This is the correct interpretation from paper
                self.sop_count += spikes

    def register_ann_hooks(self, model):
        """Register hooks for ANN model (FLOP counting)"""
        hooks = []
        for module in model.modules():
            if isinstance(module, (nn.Conv2d, nn.ConvTranspose2d, nn.ReLU, 
                                 nn.Sigmoid, nn.LeakyReLU, nn.Linear)):
                hook = module.register_forward_hook(self.ann_forward_hook)
                hooks.append(hook)
        return hooks
        
    def register_snn_hooks(self, model):
        """Register hooks for SNN model (SOP counting only)"""
        hooks = []
        for module in model.modules():
            module_type = str(type(module))
            if 'IFNode' in module_type:  # Only count SOPs from spiking neurons
                hook = module.register_forward_hook(self.snn_forward_hook)
                hooks.append(hook)
        return hooks
        
    def remove_hooks(self, hooks):
        """Remove all registered hooks"""
        for hook in hooks:
            hook.remove()

    def analyze_ann_inference(self, model_ann, test_input, device):
        """Analyze energy consumption for ANN inference (FLOPs only)"""
        self.reset_counters()
        model_ann.eval()
        
        # Register hooks to count FLOPs
        hooks = self.register_ann_hooks(model_ann)
        
        try:
            with torch.no_grad():
                _ = model_ann(test_input.to(device))
                
            ann_energy = self.flop_count * self.ann_energy_per_flop
            
            return {
                'total_flops': int(self.flop_count),
                'total_energy_joules': ann_energy,
                'energy_per_image_nj': ann_energy * 1e9,
                'operations_breakdown': {'flops': int(self.flop_count)}
            }
            
        finally:
            self.remove_hooks(hooks)

    def analyze_snn_inference(self, model_snn, test_input, device, timesteps=50):
        """Analyze energy consumption for SNN inference (SOPs only)"""
        self.reset_counters()
        model_snn.eval()
        
        # Count total neurons in all IFNodes (for accurate spike rate)
        total_neurons_in_network = 0
        for module in model_snn.modules():
            if 'IFNode' in str(type(module)):
                # This will be set during forward pass
                pass
        
        # Register hooks to count SOPs
        hooks = self.register_snn_hooks(model_snn)
        
        try:
            functional.reset_net(model_snn)
            
            with torch.no_grad():
                # SNN inference over multiple timesteps (SAME AS conversion_test.py)
                total_sops = 0.0
                total_spikes = 0.0
                
                for t in range(timesteps):
                    # Reset counters for this timestep
                    self.sop_count = 0.0
                    self.spike_count = 0.0
                    
                    if t == 0:
                        output = model_snn(test_input.to(device))
                    else:
                        output += model_snn(test_input.to(device))
                    
                    # Accumulate SOPs from this timestep
                    total_sops += self.sop_count
                    total_spikes += self.spike_count
                    
                    # Update total neurons count from first timestep
                    if t == 0:
                        total_neurons_in_network = self.get_total_neurons_count(model_snn, output)
            
            # Calculate energy from SOPs only
            snn_energy = total_sops * self.snn_energy_per_sop
            
            # Calculate spike rate using total neurons in network
            spike_rate = total_spikes / (total_neurons_in_network * timesteps) if total_neurons_in_network > 0 else 0
            
            return {
                'total_sops': int(total_sops),
                'total_spikes': int(total_spikes), 
                'spike_rate': spike_rate,
                'timesteps': timesteps,
                'total_neurons': total_neurons_in_network,
                'total_energy_joules': snn_energy,
                'energy_per_image_nj': snn_energy * 1e9,
                'operations_breakdown': {
                    'sops': int(total_sops),
                    'spikes': int(total_spikes)
                }
            }
            
        finally:
            self.remove_hooks(hooks)

    def get_total_neurons_count(self, model_snn, sample_output):
        """Calculate total neurons in all IFNodes"""
        total_neurons = 0
        
        # Store shapes during forward pass
        neuron_shapes = []
        
        def count_hook(module, input, output):
            if 'IFNode' in str(type(module)):
                neuron_shapes.append(output.shape)
        
        # Register temporary hooks
        temp_hooks = []
        for module in model_snn.modules():
            if 'IFNode' in str(type(module)):
                hook = module.register_forward_hook(count_hook)
                temp_hooks.append(hook)
        
        # Dummy forward pass to get shapes
        functional.reset_net(model_snn)
        with torch.no_grad():
            _ = model_snn(torch.randn_like(sample_output))
        
        # Remove temporary hooks
        for hook in temp_hooks:
            hook.remove()
        
        # Calculate total neurons
        for shape in neuron_shapes:
            total_neurons += np.prod(shape)
        
        return total_neurons

    def compare_models_energy(self, cfg, timesteps_list=[1, 10, 30, 50, 100]):
        """Compare energy consumption between ANN (FLOPs) and SNN (SOPs)"""
        print("=" * 60)
        print("ENERGY CONSUMPTION COMPARISON ANALYSIS")
        print("ANN: FLOPs×12.5pJ | SNN: SOPs×77fJ")
        print("=" * 60)
        
        # Load models using SAME methods as conversion_test.py
        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        
        # Load ANN model (exactly like conversion_test.py)
        model_ann = AutoEncoder(cfg).to(device)
        checkpoint_path = os.path.join(cfg.chechpoint_dir, 'model.pth')
        checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
        model_ann.load_state_dict(checkpoint['model_state_dict'])
        model_ann.eval()
        
        # Convert to SNN (exactly like conversion_test.py)
        model_snn = convert_to_snn(model_ann, cfg, device)
        
        # Create test input
        if cfg.grayscale:
            test_input = torch.randn(1, 1, cfg.patch_size, cfg.patch_size)
        else:
            test_input = torch.randn(1, 3, cfg.patch_size, cfg.patch_size)
        
        print(f"Test input shape: {test_input.shape}")
        print(f"Device: {device}")
        
        # Analyze ANN (FLOPs only)
        print(f"\n=== ANN ANALYSIS (FLOPs only) ===")
        ann_results = self.analyze_ann_inference(model_ann, test_input, device)
        
        print(f"ANN Results:")
        print(f"  Total FLOPs: {ann_results['total_flops']:,}")
        print(f"  Energy per image: {ann_results['energy_per_image_nj']:.3f} nJ")
        
        # Analyze SNN (SOPs only)
        print(f"\n=== SNN ANALYSIS (SOPs only) ===")
        snn_results = []
        
        for T in timesteps_list:
            print(f"\n--- Timesteps T={T} ---")
            snn_result = self.analyze_snn_inference(model_snn, test_input, device, T)
            snn_results.append((T, snn_result))
            
            print(f"  Total SOPs: {snn_result['total_sops']:,}")
            print(f"  Total Spikes: {snn_result['total_spikes']:,}")
            print(f"  Spike Rate: {snn_result['spike_rate']:.4f}")
            print(f"  Total Energy: {snn_result['energy_per_image_nj']:.3f} nJ")
            
            # Energy comparison
            energy_ratio = snn_result['total_energy_joules'] / ann_results['total_energy_joules']
            energy_saving = (1 - energy_ratio) * 100
            
            print(f"  Energy Ratio (SNN/ANN): {energy_ratio:.6f}")
            print(f"  Energy Saving: {energy_saving:.1f}%")
        
        # Summary table
        self.print_energy_summary(ann_results, snn_results, cfg)
        
        return ann_results, snn_results

    def print_energy_summary(self, ann_results, snn_results, cfg):
        """Print energy comparison summary in μJ (microjoules)"""
        print(f"\n" + "="*100)
        print(f"ENERGY CONSUMPTION SUMMARY - {cfg.name.upper()}")
        print(f"ANN: FLOPs×12.5pJ | SNN: SOPs×77fJ | Energy in microjoules (μJ)")
        print(f"="*100)
        
        print(f"{'Model':<8} | {'T':<3} | {'FLOPs':<12} | {'SOPs':<12} | {'Spikes':<10} | {'Rate':<6} | {'Energy(μJ)':<12} | {'Ratio':<10} | {'Saving%':<8}")
        print("-" * 100)
        
        # ANN row - convert nJ to μJ (divide by 1e3)
        ann_energy_uj = ann_results['energy_per_image_nj'] / 1e3
        print(f"{'ANN':<8} | {'-':<3} | {ann_results['total_flops']:<12,} | {'-':<12} | {'-':<10} | {'-':<6} | {ann_energy_uj:<12.4f} | {'1.000000':<10} | {'-':<8}")
        
        # SNN rows - convert nJ to μJ (divide by 1e3)
        for T, snn_result in snn_results:
            snn_energy_uj = snn_result['energy_per_image_nj'] / 1e3
            energy_ratio = snn_result['energy_per_image_nj'] / ann_results['energy_per_image_nj']
            energy_saving = (1 - energy_ratio) * 100
            
            print(f"{'SNN':<8} | {T:<3} | {'-':<12} | {snn_result['total_sops']:<12,} | {snn_result['total_spikes']:<10,} | {snn_result['spike_rate']:<6.3f} | {snn_energy_uj:<12.4f} | {energy_ratio:<10.6f} | {energy_saving:<8.1f}")
        
 
def load_model(cfg):
    """Load trained ANN model (same as conversion_test.py)"""
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = AutoEncoder(cfg).to(device)
    checkpoint_path = os.path.join(cfg.chechpoint_dir, 'model.pth')
    
    if not os.path.exists(checkpoint_path):
        raise FileNotFoundError(f"Model file not found: {checkpoint_path}")
        
    checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)
    model.load_state_dict(checkpoint['model_state_dict'])
    model.eval()
    
    print(f"Loaded ANN checkpoint: {checkpoint_path}")
    return model, device


def create_calibration_dataloader(cfg):
    """Create dataloader for SNN conversion calibration (same as conversion_test.py)"""
    good_files = glob(cfg.train_data_dir + '/*png')
    
    if not good_files:
        raise ValueError(f"No training files found in {cfg.train_data_dir}")
    
    dataset = CalibrationDataset(good_files, cfg.grayscale, cfg.patch_size)
    dataloader = DataLoader(dataset, batch_size=64, shuffle=False, num_workers=0)
    
    print(f"Using {len(dataset)} training samples for calibration")
    return dataloader


def convert_to_snn(model_ann, cfg, device):
    """Pure SpikingJelly ANN to SNN conversion (EXACTLY same as conversion_test.py)"""
    print("Converting ANN to SNN using pure SpikingJelly...")
    
    # Step 1: Remove Sigmoid layer (SpikingJelly can't handle it)
    decoder_layers = list(model_ann.decoder.children())
    if isinstance(decoder_layers[-1], nn.Sigmoid):
        model_ann.decoder = nn.Sequential(*decoder_layers[:-1])
        print("Removed Sigmoid layer before conversion")
    
    # Step 2: Create calibration dataloader
    calib_dataloader = create_calibration_dataloader(cfg)
    
    # Step 3: Use pure SpikingJelly converter
    converter = ann2snn.Converter(
        dataloader=calib_dataloader, 
        device=device, 
        mode='max',
        momentum=0.1
    )
    
    # Step 4: Convert to SNN - this will replace ReLU with IFNode + VoltageScaler
    model_snn = converter(model_ann)
    print("SpikingJelly ANN to SNN conversion completed")
    
    return model_snn


def test_energy_comparison():
    """Main function to test energy comparison"""
    cfg = Options().parse()
    
    analyzer = EnergyAnalyzer()
    
    # Test with different timesteps
    timesteps_to_test = [1, 20, 40, 60, 80, 100, 300]
    
    ann_results, snn_results = analyzer.compare_models_energy(cfg, timesteps_to_test)

if __name__ == '__main__':
    test_energy_comparison()